// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: files/grpc-protos/example.proto

package grpc_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExampleRequest) Reset() {
	*x = GetExampleRequest{}
	mi := &file_files_grpc_protos_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExampleRequest) ProtoMessage() {}

func (x *GetExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExampleRequest.ProtoReflect.Descriptor instead.
func (*GetExampleRequest) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_example_proto_rawDescGZIP(), []int{0}
}

func (x *GetExampleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExampleResponse) Reset() {
	*x = GetExampleResponse{}
	mi := &file_files_grpc_protos_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExampleResponse) ProtoMessage() {}

func (x *GetExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExampleResponse.ProtoReflect.Descriptor instead.
func (*GetExampleResponse) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_example_proto_rawDescGZIP(), []int{1}
}

func (x *GetExampleResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetExampleResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_files_grpc_protos_example_proto protoreflect.FileDescriptor

const file_files_grpc_protos_example_proto_rawDesc = "" +
	"\n" +
	"\x1ffiles/grpc-protos/example.proto\x12\x05grpcs\"#\n" +
	"\x11GetExampleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"K\n" +
	"\x12GetExampleResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total2U\n" +
	"\x0eExampleService\x12C\n" +
	"\n" +
	"GetExample\x12\x18.grpcs.GetExampleRequest\x1a\x19.grpcs.GetExampleResponse\"\x00B\x0fZ\r./grpc-protosb\x06proto3"

var (
	file_files_grpc_protos_example_proto_rawDescOnce sync.Once
	file_files_grpc_protos_example_proto_rawDescData []byte
)

func file_files_grpc_protos_example_proto_rawDescGZIP() []byte {
	file_files_grpc_protos_example_proto_rawDescOnce.Do(func() {
		file_files_grpc_protos_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_files_grpc_protos_example_proto_rawDesc), len(file_files_grpc_protos_example_proto_rawDesc)))
	})
	return file_files_grpc_protos_example_proto_rawDescData
}

var file_files_grpc_protos_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_files_grpc_protos_example_proto_goTypes = []any{
	(*GetExampleRequest)(nil),  // 0: grpcs.GetExampleRequest
	(*GetExampleResponse)(nil), // 1: grpcs.GetExampleResponse
}
var file_files_grpc_protos_example_proto_depIdxs = []int32{
	0, // 0: grpcs.ExampleService.GetExample:input_type -> grpcs.GetExampleRequest
	1, // 1: grpcs.ExampleService.GetExample:output_type -> grpcs.GetExampleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_files_grpc_protos_example_proto_init() }
func file_files_grpc_protos_example_proto_init() {
	if File_files_grpc_protos_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_files_grpc_protos_example_proto_rawDesc), len(file_files_grpc_protos_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_files_grpc_protos_example_proto_goTypes,
		DependencyIndexes: file_files_grpc_protos_example_proto_depIdxs,
		MessageInfos:      file_files_grpc_protos_example_proto_msgTypes,
	}.Build()
	File_files_grpc_protos_example_proto = out.File
	file_files_grpc_protos_example_proto_goTypes = nil
	file_files_grpc_protos_example_proto_depIdxs = nil
}
