// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: files/grpc-protos/store.proto

package grpc_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request messages
type GetStoreByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreByIDRequest) Reset() {
	*x = GetStoreByIDRequest{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreByIDRequest) ProtoMessage() {}

func (x *GetStoreByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreByIDRequest.ProtoReflect.Descriptor instead.
func (*GetStoreByIDRequest) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{0}
}

func (x *GetStoreByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // retail or grosir
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoreRequest) Reset() {
	*x = CreateStoreRequest{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoreRequest) ProtoMessage() {}

func (x *CreateStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoreRequest.ProtoReflect.Descriptor instead.
func (*CreateStoreRequest) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStoreRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateStoreRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UpdateStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // retail or grosir
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStoreRequest) Reset() {
	*x = UpdateStoreRequest{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoreRequest) ProtoMessage() {}

func (x *UpdateStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoreRequest.ProtoReflect.Descriptor instead.
func (*UpdateStoreRequest) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStoreRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateStoreRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DeleteStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoreRequest) Reset() {
	*x = DeleteStoreRequest{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoreRequest) ProtoMessage() {}

func (x *DeleteStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteStoreRequest) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListStoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoresRequest) Reset() {
	*x = ListStoresRequest{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresRequest) ProtoMessage() {}

func (x *ListStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresRequest.ProtoReflect.Descriptor instead.
func (*ListStoresRequest) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{4}
}

func (x *ListStoresRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListStoresRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Response messages
type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // retail or grosir
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{5}
}

func (x *StoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoreResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StoreResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StoreResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StoreResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *StoreResponse) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type StoreErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreErrorResponse) Reset() {
	*x = StoreErrorResponse{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreErrorResponse) ProtoMessage() {}

func (x *StoreErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreErrorResponse.ProtoReflect.Descriptor instead.
func (*StoreErrorResponse) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{6}
}

func (x *StoreErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StoreErrorResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type GetStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Data          *StoreResponse         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         *StoreErrorResponse    `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreResponse) Reset() {
	*x = GetStoreResponse{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreResponse) ProtoMessage() {}

func (x *GetStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreResponse.ProtoReflect.Descriptor instead.
func (*GetStoreResponse) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{7}
}

func (x *GetStoreResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetStoreResponse) GetData() *StoreResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetStoreResponse) GetError() *StoreErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListStoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Data          []*StoreResponse       `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Error         *StoreErrorResponse    `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoresResponse) Reset() {
	*x = ListStoresResponse{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresResponse) ProtoMessage() {}

func (x *ListStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresResponse.ProtoReflect.Descriptor instead.
func (*ListStoresResponse) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{8}
}

func (x *ListStoresResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListStoresResponse) GetData() []*StoreResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListStoresResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListStoresResponse) GetError() *StoreErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type CreateStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Data          *StoreResponse         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         *StoreErrorResponse    `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoreResponse) Reset() {
	*x = CreateStoreResponse{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoreResponse) ProtoMessage() {}

func (x *CreateStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoreResponse.ProtoReflect.Descriptor instead.
func (*CreateStoreResponse) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{9}
}

func (x *CreateStoreResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateStoreResponse) GetData() *StoreResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateStoreResponse) GetError() *StoreErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Data          *StoreResponse         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         *StoreErrorResponse    `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStoreResponse) Reset() {
	*x = UpdateStoreResponse{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoreResponse) ProtoMessage() {}

func (x *UpdateStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoreResponse.ProtoReflect.Descriptor instead.
func (*UpdateStoreResponse) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStoreResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateStoreResponse) GetData() *StoreResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateStoreResponse) GetError() *StoreErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         *StoreErrorResponse    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoreResponse) Reset() {
	*x = DeleteStoreResponse{}
	mi := &file_files_grpc_protos_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoreResponse) ProtoMessage() {}

func (x *DeleteStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_grpc_protos_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoreResponse.ProtoReflect.Descriptor instead.
func (*DeleteStoreResponse) Descriptor() ([]byte, []int) {
	return file_files_grpc_protos_store_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteStoreResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteStoreResponse) GetError() *StoreErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_files_grpc_protos_store_proto protoreflect.FileDescriptor

const file_files_grpc_protos_store_proto_rawDesc = "" +
	"\n" +
	"\x1dfiles/grpc-protos/store.proto\x12\x05grpcs\"%\n" +
	"\x13GetStoreByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x12CreateStoreRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"n\n" +
	"\x12UpdateStoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"$\n" +
	"\x12DeleteStoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x11ListStoresRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xc6\x01\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\a \x01(\tR\tdeletedAt\"O\n" +
	"\x12StoreErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\"\x8e\x01\n" +
	"\x10GetStoreResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.grpcs.StoreResponseR\x04data\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.grpcs.StoreErrorResponseR\x05error\"\xa6\x01\n" +
	"\x12ListStoresResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12(\n" +
	"\x04data\x18\x02 \x03(\v2\x14.grpcs.StoreResponseR\x04data\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12/\n" +
	"\x05error\x18\x04 \x01(\v2\x19.grpcs.StoreErrorResponseR\x05error\"\x91\x01\n" +
	"\x13CreateStoreResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.grpcs.StoreResponseR\x04data\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.grpcs.StoreErrorResponseR\x05error\"\x91\x01\n" +
	"\x13UpdateStoreResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.grpcs.StoreResponseR\x04data\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.grpcs.StoreErrorResponseR\x05error\"g\n" +
	"\x13DeleteStoreResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x19.grpcs.StoreErrorResponseR\x05error2\xee\x02\n" +
	"\fStoreService\x12A\n" +
	"\bGetStore\x12\x1a.grpcs.GetStoreByIDRequest\x1a\x17.grpcs.GetStoreResponse\"\x00\x12C\n" +
	"\n" +
	"ListStores\x12\x18.grpcs.ListStoresRequest\x1a\x19.grpcs.ListStoresResponse\"\x00\x12F\n" +
	"\vCreateStore\x12\x19.grpcs.CreateStoreRequest\x1a\x1a.grpcs.CreateStoreResponse\"\x00\x12F\n" +
	"\vUpdateStore\x12\x19.grpcs.UpdateStoreRequest\x1a\x1a.grpcs.UpdateStoreResponse\"\x00\x12F\n" +
	"\vDeleteStore\x12\x19.grpcs.DeleteStoreRequest\x1a\x1a.grpcs.DeleteStoreResponse\"\x00B\x0fZ\r./grpc-protosb\x06proto3"

var (
	file_files_grpc_protos_store_proto_rawDescOnce sync.Once
	file_files_grpc_protos_store_proto_rawDescData []byte
)

func file_files_grpc_protos_store_proto_rawDescGZIP() []byte {
	file_files_grpc_protos_store_proto_rawDescOnce.Do(func() {
		file_files_grpc_protos_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_files_grpc_protos_store_proto_rawDesc), len(file_files_grpc_protos_store_proto_rawDesc)))
	})
	return file_files_grpc_protos_store_proto_rawDescData
}

var file_files_grpc_protos_store_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_files_grpc_protos_store_proto_goTypes = []any{
	(*GetStoreByIDRequest)(nil), // 0: grpcs.GetStoreByIDRequest
	(*CreateStoreRequest)(nil),  // 1: grpcs.CreateStoreRequest
	(*UpdateStoreRequest)(nil),  // 2: grpcs.UpdateStoreRequest
	(*DeleteStoreRequest)(nil),  // 3: grpcs.DeleteStoreRequest
	(*ListStoresRequest)(nil),   // 4: grpcs.ListStoresRequest
	(*StoreResponse)(nil),       // 5: grpcs.StoreResponse
	(*StoreErrorResponse)(nil),  // 6: grpcs.StoreErrorResponse
	(*GetStoreResponse)(nil),    // 7: grpcs.GetStoreResponse
	(*ListStoresResponse)(nil),  // 8: grpcs.ListStoresResponse
	(*CreateStoreResponse)(nil), // 9: grpcs.CreateStoreResponse
	(*UpdateStoreResponse)(nil), // 10: grpcs.UpdateStoreResponse
	(*DeleteStoreResponse)(nil), // 11: grpcs.DeleteStoreResponse
}
var file_files_grpc_protos_store_proto_depIdxs = []int32{
	5,  // 0: grpcs.GetStoreResponse.data:type_name -> grpcs.StoreResponse
	6,  // 1: grpcs.GetStoreResponse.error:type_name -> grpcs.StoreErrorResponse
	5,  // 2: grpcs.ListStoresResponse.data:type_name -> grpcs.StoreResponse
	6,  // 3: grpcs.ListStoresResponse.error:type_name -> grpcs.StoreErrorResponse
	5,  // 4: grpcs.CreateStoreResponse.data:type_name -> grpcs.StoreResponse
	6,  // 5: grpcs.CreateStoreResponse.error:type_name -> grpcs.StoreErrorResponse
	5,  // 6: grpcs.UpdateStoreResponse.data:type_name -> grpcs.StoreResponse
	6,  // 7: grpcs.UpdateStoreResponse.error:type_name -> grpcs.StoreErrorResponse
	6,  // 8: grpcs.DeleteStoreResponse.error:type_name -> grpcs.StoreErrorResponse
	0,  // 9: grpcs.StoreService.GetStore:input_type -> grpcs.GetStoreByIDRequest
	4,  // 10: grpcs.StoreService.ListStores:input_type -> grpcs.ListStoresRequest
	1,  // 11: grpcs.StoreService.CreateStore:input_type -> grpcs.CreateStoreRequest
	2,  // 12: grpcs.StoreService.UpdateStore:input_type -> grpcs.UpdateStoreRequest
	3,  // 13: grpcs.StoreService.DeleteStore:input_type -> grpcs.DeleteStoreRequest
	7,  // 14: grpcs.StoreService.GetStore:output_type -> grpcs.GetStoreResponse
	8,  // 15: grpcs.StoreService.ListStores:output_type -> grpcs.ListStoresResponse
	9,  // 16: grpcs.StoreService.CreateStore:output_type -> grpcs.CreateStoreResponse
	10, // 17: grpcs.StoreService.UpdateStore:output_type -> grpcs.UpdateStoreResponse
	11, // 18: grpcs.StoreService.DeleteStore:output_type -> grpcs.DeleteStoreResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_files_grpc_protos_store_proto_init() }
func file_files_grpc_protos_store_proto_init() {
	if File_files_grpc_protos_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_files_grpc_protos_store_proto_rawDesc), len(file_files_grpc_protos_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_files_grpc_protos_store_proto_goTypes,
		DependencyIndexes: file_files_grpc_protos_store_proto_depIdxs,
		MessageInfos:      file_files_grpc_protos_store_proto_msgTypes,
	}.Build()
	File_files_grpc_protos_store_proto = out.File
	file_files_grpc_protos_store_proto_goTypes = nil
	file_files_grpc_protos_store_proto_depIdxs = nil
}
